### ISSUE TITLE
Concepto de Diseño - Germán

### ISSUE THREAD

**Issue by Gabo-7** [Gabo-7/Design1#10]
+ 3 conceptos y 30 ideas con el concepto.

**Comment by ghost** [comment]
CONCEPTO DE DISEÑO

Soluciones relajantes a problemas estresantes

Le ponemos diversion a tus necesidades

Juegos que inspiran alegría

**Comment by ghost** [comment]
Animación del gato en primera persona para ver como cambia lo que ve después de drogarlo.
El gato atacando todo lo que se le acerque y al drogarlo se vuelve amistoso.
Varios gatos andando en círculos y estrellándose (tipo carros chocones) y al drogarlos se duermen.
Un juego en el que el gato huye de algo y drogarse le da energía.

**Comment by GermanD16** [comment]
El gato atacando todo lo que se le acerque y al drogarlo se vuelve amistoso
