### ISSUE TITLE
Lista de Recursos

### ISSUE THREAD

**Issue by Gabo-7** [Gabo-7/Design1#12]

**Comment by Tiago3198** [comment]
- Computador Z9MARK-17
MB: Gigabyte GA-AB350-Gaming3
CPU: Procesador AMD Ryzen 5 1600, Six-Core Processor. 3.5 Ghz (With overclock).
RAM: 16 GB DDR4, 3200 Mhz.
GPU: Zotac (single fan) GTX1060 6GB.
SSD: Kingston 240 GB.
HDD: Seagate Barracuda 1TB.

**Comment by Gabo-7** [comment]
CPU: Intel(R) Core(TM) i7-3770K CPU @3.50 GHz   3.90 GHz.
RAM: 16 GB DDR3.
GPU: AMD Radeon HD 7900 Series.
