### ISSUE TITLE
Estudio de mercado

### ISSUE THREAD

**Issue by Gabo-7** [Gabo-7/Design1#13]

**Comment by Tiago3198** [comment]
Registradas y avaladas por The International Cat Association (Tica), hay un poco más de 100 razas de gatos en el mundo. La mayoría son el resultado de cruces hechos por el hombre y por lo general, entre sus ancestros, podría encontrarse un gen del siamés. Sí, este, podría decirse, es el rey de los gatos.

Estas son esas razas que se crían en el país.

1. Maine Coon. Los gatos de esta raza son considerados los felinos domésticos más grandes del mundo. Llegan a medir 1,20 metros de la punta de la nariz hasta la punta de la cola, y a pesar de 11 a 12 kilos. Físicamente se caracteriza por que tienen linces (pelos largos) en la punta de las orejas. Su temperamento es dulce y familiar, aunque por su aspecto parece un poco salvaje.

2. Bengalí. Estos tienen una característica que es como su marca: las rosetas o dibujos en su cuerpo, que hacen que se parezcan al leopardo. Tienen muy latente su instinto salvaje, por lo que marcan con mucha insistencia su terrero.

3. Persa. Son los únicos gatos de pelo largo, y a diferencia de otras razas de felinos, no tienen una subcapa de pelo. Su cara también es muy característica: es chata y la nariz está justo en la mitad de los ojos (a la misma altura). Son gatos muy tranquilos, duermen a pierna suelta, por lo que les dicen gatos de sofá, y raramente maúllan. No les gusta pasar mucho tiempo solos.

4. Himalayo. Esta raza es el resultado de cruzar un siamés con un persa. Tiene puntos de color en su pelaje, y la punta de las patas, de la cola y de la orejas es de un color distinto al del pelaje, herencia del siamés, como los ojos azules. Su temperamento corresponde más al persa.

5. Scotish fold. La cabeza redonda, así como sus pies, es característica de esta raza. Tiene la cola gruesa, las orejas plegadas, la nariz chata y los pómulos salientes, como si tuviera cachetes. Son gatos muy activos, pero por su peso y estructura gruesa, realiza movimientos más suave.

6. Común europeo de pelo corto. El gato común europeo, como su nombre indica, es originario de Europa. Fue reconocido como raza el 1 de enero de 1983. Es fuerte, tiene un sólido sistema inmunológico y se adapta fácilmente a cualquier ambiente.

7. Criollo. En realidad no es una raza, sino la mezcla de varias, sin que se conozcan cómo se dieron esos cruces. Es el gato más común en Colombia.
