### ISSUE TITLE
Taxonomía de gatos

### ISSUE THREAD

**Issue by Gabo-7** [Gabo-7/Design1#14]

**Comment by ghost** [comment]
TAXONOMÍA

Reino                    Animal
Filo                       Cordados
Subfilo                 Vertebrados
Super-clase          Tetrapoda
Clase                    Mamíferos
Sub-clase             Terios
Orden                   Carnívoros
Sub-orden            Feliformes
Familia                  Félidos
Sub-familia           Felinos
Genero                 Felis
Especie                 F. Silvestris
Sub-especie         F. S. Catus

**Comment by ghost** [comment]
ANATOMÍA

El ágil movimiento de los gatos se debe a su sistema oseo, muscular, y a la planta de sus patas. El primer elemento, sus sistema oseo, esta compuesto por mas huesos que el de un ser humano, esto debido al numero de vertebras presentes en la cola, la cual les ayuda a mantener el equilibrio; y en la espalda, las cuales no están rígidamente unidas, sino conectadas por medio de músculos y tendones lo que les da mucha mas flexibilidad permitiendoles así arquearse o estirarse según lo necesiten. En segundo lugar, su sistema muscular, compuesto por mas de 500 músculos le otorga a su sistema oseo una gran capacidad de movimiento, ademas que una gran parte de la fuerza de los felinos se centra en sus patas traseras, permitiendoles tener el impulso suficiente para dar grandes saltos o alcanzar granes velocidades (hasta 45 km/h). Y por ultimo, las patas de los gatos terminan en unas almohadillas de piel ideales para amortiguar caídas así como para evitar deslizarse a la hora de caminar, a pesar de tener otras funciones como detectar vibraciones o nivelar la temperatura; y por otro lado, sus garras sirven como un gancho a la hora de trepar o correr.
