### ISSUE TITLE
Concepto de Diseño - Laura

### ISSUE THREAD

**Issue by Gabo-7** [Gabo-7/Design1#8]
+ 3 conceptos y 30 ideas con el concepto.

**Comment by Laurg** [comment]
### **Concepto** de diseño:  Las dos caras del gato

> Con este concepto se busca utilizar la analogía "las dos caras de la moneda" dando a entender que el efecto del catnip en los gatos, puede generar cambios radicales en la personalidad y /o estado anímico del felino por unos minutos
     

###                 Animación interaciva: ideas

- El usuario inicia la animacion dandole el producto al gato, este luego se imagina siendo un "personaje historico".
- El usuario le da el catnip al gato, este se convierte en una moneda y se puede hacer "cara o sello"
- Luego de dado el catnip al gato, se deben cerrar las ventanas y/o puertas del lugar.
- Se debe bañar el gato, y se elige entre rociar agua o rociar ctnip en el lugar para bañarle.
- Se debe  intentar quitar accesorios al gato antes de que el efecto del catnip finalice.
- En un lapso de máximo 5 segundos rociar catnip en un juguete para tranquilizarle o razguñara al usuario.
- Apunary tratar de disparar  con el catnip (splash) a un objeto que el gato no deja de molestar.
- Mantener relajado tratando de hacer que este huela el catnip.
- Mantener despierto al gato aplicando catnip a su alrededor.
- Evitar que el gato razgue un sofá aplicando catnip en la alfombra antes de que lo haga.
- Luego de dar el catnip, intentar seleccionar el color correcto del gato, el cual comenzará a variar.
- Impedir que el gato  arroje cosas luego de que se le da catnip.
- Despues de que el gato  consume el catnip, comodarle  eviando que se caiga de un sofá
