### ISSUE TITLE
Concepto de Diseño - Santiago

### ISSUE THREAD

**Issue by Gabo-7** [Gabo-7/Design1#9]
+ 3 conceptos y 30 ideas con el concepto.

**Comment by Tiago3198** [comment]
-	Un juego de carreras sobre el aura boreal donde el usuario conduce un carro en forma de gato.
-	En la parte inferior aparece un gato con un canasto, el usuario debe recoger hojas de menta que caen del cielo.
-	El usuario debe intentar peinar al gato y cada vez que esté lo trate de morder, el usuario lo tranquilizará con el spray.
-	El gato luego de probar el spray saldrá volando al cielo, el usuario debe quitar los obstáculos que hay en el camino para que el gato llegue al tesoro (Catnip).
-	El gato luego de probar el Catnip saltará de la ventana a un “trampolín mágico” en el suelo, en donde saltará varias veces recogiendo hojas y ramillos de Catnip.
-	Sobre una barra deslizadora van pasando entre hojas de Catnip, el Catnip en spray y “pepinillos”, el gato debe coger el Catnip pero evitar los pepinillos.
-	El gato correrá por un circuito ambientado en un espacio “mágico”, esquivando obstáculos y recogiendo Catnip en spray.
-	Una considerable cantidad de gatos tratarán de acercarse agresivamente al usuario, este deberá calmarlos con objetos untados de Catnip.
-	El gato bajo los efectos del Catnip volará por el espacio en busca de spray Xtreme.
-	El usuario debe conectar un extremo de la tubería hasta la posición del gato, de la tubería caerá el líquido Catnip dispensado en spray.
-	Hay dos gatos a punto de pelar, el usuario debe estar atento para aplicar Catnip apenas los dos gatos empiecen a pelear para acabar rápidamente con la contienda.
-	El usuario tendrá la oportunidad de customizar al gato quién está bajo los efectos del Catnip con diferentes trajes aleatorios.
-	Al gato se le acaba el Catnip, lo cual el usuario debe resolver unos acertijos para ganar dinero para luego comprar Catnip y hacer feliz al gato.
-	El gato irritado sale de la casa, el usuario debe perseguirlo y calmarlo con Catnip.
-	El usuario consume sin querer Catnip luego de estar jugando con su gato, debido al efecto se transporta a un mundo mágico en donde su gato habla.

CONCEPTOS
- “Euforia a un ‘splash’ de distancia”
- “Una dimensión de fantasía para tu gato encerrado en una botella”
